#Generated by Fabric Compiler ( version 2019.1-patch2 <build 42169> ) at Mon May 13 18:39:13 2019

project -load "D:/example_ziguang/hdmi_test _char/synthesize/synplify_impl/../synplify_pro.prj"
open_file "D:/example_ziguang/hdmi_test _char/synthesize/synplify_impl/synplify.srs"
